### ISSUE TITLE
原作者看到了

### ISSUE THREAD

**Issue by wong2** [justjavac/proxy-www#15]
很不理解你这种行为，拿别人Twitter上的创意和代码创建repo，连credit也是今天有人提出来才加的

![image](https://user-images.githubusercontent.com/321947/116770321-8984a800-aa75-11eb-9417-b81520df221f.png)

**Comment by carsonxw** [comment]
GG I saw it as well. Just renamed the variable.
Original post: https://twitter.com/rauchg/status/1388231666771001346?s=21

![B799DB38-1A55-4234-A07F-693A81EE5270](https://user-images.githubusercontent.com/37298918/116772297-64059780-aa91-11eb-9c49-fb2d40fe4928.png)

**Comment by justjavac** [comment]
之前看到群里分享的图片，所以建了这个 repo，具体我也不知道原出处。今天收到提醒，知道了原作者，于是加了出处
